name: "souji-action"
description: "Clean up the GitHub Action cache"
author: "4m-mazi"

# Add your action's branding here. This will appear on the GitHub Marketplace.
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: "wind"
  color: "purple"

# Define your inputs here.
inputs:
  repo-token:
    description: "The GitHub token used to manage repository action cache"
    required: false
    default: ${{ github.token }}

# Define your outputs here.

runs:
  using: node20
  main: dist/index.js
