name: 'Souji Action'
description: 'Clean up the GitHub Action cache'
author: '4m-mazi'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'wind'
  color: 'purple'

# Define your inputs here.
inputs:
  repo-token:
    description: 'The GitHub token used to manage repository action cache'
    required: true
    default: ${{ github.token }}
  branch-names:
    description: 'List of branch(ref) names with caches to be deleted (e.g., `main refs/pull/123/merge refs/tags/1.0.0`)'
    required: false
  dry-run:
    description: 'If `true`, dry-run caches deletion.'
    required: false
    default: 'false'

# Define your outputs here.

runs:
  using: node20
  main: dist/index.js
