on:
  push:
    branches: main

name: release-please

permissions: {}

jobs:
  release-please:
    if: github.repository_owner == '4m-mazi'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
        with:
          app-id: ${{ secrets.MAZI_RELEASE_APP_ID }}
          private-key: ${{ secrets.MAZI_RELEASE_APP_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v4.1.1
        id: release-please
        with:
          token: ${{ steps.generate_token.outputs.token }}
          config-file: .github/files/release-please/release-please-config.json
          manifest-file: .github/files/release-please/.release-please-manifest.json
          skip-github-pull-request:
            ${{ startsWith(github.event.head_commit.message, 'release:') &&
            github.event.head_commit.author.name == format('{0}[bot]',
            steps.generate_token.outputs.app-slug) }}

  move-tags:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          sparse-checkout: ''
          sparse-checkout-cone-mode: false
          fetch-tags: true
      - uses: fischerscode/tagger@5ca3fa63ce3003fb7183cae547644b29f3b632be # v0.2.0
        with:
          prefix: v
          tag: ${{ needs.release-please.outputs.tag_name }}
