on:
  push:
    branches: main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == '4m-mazi'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4.0.2
        id: release-please
        with:
          config-file: .github/files/release-please/release-please-config.json
          manifest-file: .github/files/release-please/.release-please-manifest.json
          skip-github-pull-request:
            ${{ startsWith(github.event.head_commit.message, 'release:') &&
            github.event.head_commit.author.name == 'github-actions[bot]' }}
